libraries:                                      # Library mappings must have a colon (:) placed after them
  Filme:
    report_path: config/Filme_missing.yml
    metadata_path:
    - pmm: imdb
    - pmm: trakt
    - pmm: tmdb
    - pmm: oscars
    - pmm: golden
    - pmm: emmy
    - pmm: seasonal
    - pmm: franchise
      template_variables:
        use_separator: false
    - pmm: universe
      template_variables:
        use_separator: false
    - pmm: resolution
      template_variables:
        use_separator: false

  Serien:
    report_path: config/Serien_missing.yml
    metadata_path:
    - pmm: imdb
    - pmm: trakt
    - pmm: tmdb
    - pmm: golden
    - pmm: emmy
    - pmm: franchise
      template_variables:
        use_separator: false
    - pmm: universe
      template_variables:
        use_separator: false

playlist_files:
- pmm: playlist
  template_variables:
    libraries: Movies, Serien

settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: true
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: true
  create_asset_folders: true
  delete_below_minimum: false
  tvdb_language: default
  show_missing_assets: true
  show_missing_season_assets: false
  delete_not_scheduled: false
  only_filter_missing: false
  ignore_ids:
  ignore_imdb_ids:
  asset_depth: 0
  dimensional_asset_rename: false
  show_options: false
  minimum_items: 1
  download_url_assets: true
  default_collection_order:
  verify_ssl: false
  playlist_sync_to_users: all
  show_missing_episode_assets: false
  show_asset_not_needed: true
  item_refresh_delay: 0
  custom_repo:
  prioritize_assets: false
  playlist_report: true
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
plex:                                           # Can be individually specified per library as well
  url: https://10.20.30.40:32400
  token: ****
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true
  db_cache:
  verify_ssl:
tmdb:
  apikey: ****
  language: de
  cache_expiration: 60
  region:
tautulli:                                       # Can be individually specified per library as well
  url: http://10.20.30.40:8181
  apikey: ****
trakt:
  client_id: ****
  client_secret: ****
  authorization:
    access_token: ****
    token_type: Bearer
    expires_in: 7889237
    refresh_token: ****
    scope: public
    created_at: 1689998460
  pin: